### ISSUE TITLE
Use `here` library for system/machine agnostic filepaths rather than manually changing paths

### ISSUE THREAD

**Issue by derrik-gratz** [bbi-lab/SASC#2]
The `here` library can set working directories and paths relative to either projects or individual files. You can run something like `here::i_am()` in the source file to set working dir and define paths relative to that with `here('<relative_paths>')`. It can help clean up path management stuff for scripts like this that are meant to be shared. Just an idea :)

**Comment by derrik-gratz** [comment]
https://here.r-lib.org/index.html

**Comment by athuyvo** [comment]
Thanks for the suggestion, Derrik! The scripts have been updated
